spring.application.name=rentrella

# DB connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail
spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-validity-ms=${JWT_ACCESS_TOKEN_VALIDITY_MS:1800000}
app.jwt.refresh-token-validity-ms=${JWT_REFRESH_TOKEN_VALIDITY_MS:1209600000}
app.auth.email-code-validity-minutes=${EMAIL_CODE_VALIDITY_MINUTES:3}
app.auth.email-code-max-failed-attempts=${EMAIL_CODE_MAX_FAILED_ATTEMPTS:5}
app.mail.from=${MAIL_FROM:no-reply@rentrella.local}
